# Generated by Django 5.0.6 on 2024-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_num', models.CharField(max_length=20, verbose_name='Designation Number')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('prop_name', models.CharField(max_length=250, verbose_name='Property Name')),
                ('phy_addr', models.CharField(max_length=500, verbose_name='Physical Address')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip')),
                ('phone', models.CharField(max_length=16, verbose_name='Main Phone Number')),
                ('web', models.URLField(max_length=250, verbose_name='Web Address')),
                ('lodge_type', models.CharField(max_length=100, verbose_name='Type of Lodging Facility')),
                ('palm_level', models.CharField(max_length=10, verbose_name='Palm Level')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
            ],
        ),
    ]
