# Generated by Django 5.0.6 on 2024-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldestination',
            name='lodge_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Type of Lodging Facility'),
        ),
    ]
